export default function Terms() {
    return (
        <div style={styles.container}>
      <h2>WEBSITE TERMS OF USE</h2>
      <p>Thank you for your interest in the Blue Spruce Concepts, Inc. website located at www.bluesprucecopymachines.com (the “Site”) provided to you by Blue Spruce Concepts, Inc. (“Sponsor”), as well as all related web sites, networks, downloadable software, and other software, products and services provided by us and on which a link to these Terms of Use is displayed (collectively, our “Service”). This Terms of Use, along with the Blue Spruce Concepts, Inc. Privacy Policy and any other applicable policies, as may be updated from time to time, govern your use of the Service. This Terms of Use is a legally binding contract between you and Sponsor regarding your use of the Service.</p>
      <p>Certain aspects of the Service may be provided by one or more third parties. Such third parties may have their own policies and end user license agreements (collectively, “Third Party Policies and EULAs”) that apply to your use of the Service. Nothing in this Terms of Use is intended to modify or limit such Third Party Policies and EULAs. This Terms of Use only applies to the Service to Sponsor.</p>
      <p><strong>PLEASE READ THE TERMS OF USE CAREFULLY. BY ACCESSING OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE TERMS OF USE. IF YOU DO NOT AGREE, YOU MAY NOT USE THE SERVICE.</strong></p>
      <p>You acknowledge and agree that, as provided in greater detail in the Terms of Use:</p>
      <ul>
        <li>your use of the Service may be subject to separate third party terms of use/service and fees;</li>
        <li>you consent to the collection and use of your personally identifiable information and information about your location in accordance with the Blue Spruce Concepts, Inc. Privacy Policy and the privacy policies of third parties;</li>
        <li>the Service is provided “as is” without warranties of any kind and Sponsor’s liability to you is limited;</li>
        <li>disputes arising hereunder will be resolved by binding arbitration, AND BY ACCEPTING THIS TERMS OF USE, YOU AND SPONSOR ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract (except for matters that may be taken to small claims court). Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury and your claims cannot be brought as a class action. Please review the Arbitration Agreement below for the details regarding your agreement to arbitrate any disputes with Sponsor;</li>
        <li>access to certain features of the Service may require access to information about the location of your device, such as GPS coordinates.</li>
        <li>by creating an account on our service or otherwise accessing, contributing or activating content on the Service, you agree to subscribe to newsletters, marketing, promotional or sponsored materials and other information we may send which may take a variety of forms and methods inclusive of, but not limited to, electronic communications such as email and SMS/text messaging. Receipt of such sponsored material may create additional fees and charges with your mobile or data provider. You are responsible for all such costs. However, you may opt-out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email or text message we may send.</li>
      </ul>
      <h3>1. User Content.</h3>
      <h3>1.1 User Content Generally.</h3>
      <p>Certain features of the Service may permit users to post content, including messages, reviews, photos, video, images, folders, data, text, and other types of works (collectively, “User Content”) and to publish User Content on the Service.</p>

      <h3>1.2 Limited License Grant.</h3>
      <p>By posting or publishing User Content, you grant Sponsor a perpetual, worldwide, non-exclusive, royalty-free right and license (with the right to sublicense) to host, store, transfer, display, perform, reproduce, modify, and distribute your User Content, in whole or in part, in any media formats and through any media channels (now known or hereafter developed). Any such use of your User Content by Sponsor may be without any compensation paid to you.</p>

      <h3>1.3 Limited License Grant to Other Users.</h3>
      <p>By posting and sharing User Content with another user of the Service, you hereby grant that user a non-exclusive license to access and use such User Content as permitted by this Terms of Use and the functionality of the Service.</p>

      <h3>1.4 User Content Representations and Warranties.</h3>
      <p>You are solely responsible for your User Content and the consequences of posting or publishing User Content. By posting and publishing User Content, you affirm, represent, and warrant that:</p>
      <ul>
        <li>you are the creator and owner of, or have the necessary licenses, rights, consents, and permissions to use and to authorize Sponsor and users of the Service to use and distribute your User Content as necessary to exercise the licenses granted by you in this Section 1 and in the manner contemplated by Sponsor and this Terms of Use; and</li>
        <li>your User Content, and use of your User Content as contemplated by this Terms of Use, does not and will not: (i) infringe, violate, or misappropriate any third party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; or (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person.</li>
      </ul>
      <p>By creating an account with us, you guarantee you are 18 years of age or older and all personal information you provide is accurate.</p>

      <h3>1.5 User Content Disclaimer.</h3>
      <p>Sponsor is under no obligation to edit or control User Content that you or other users post or publish, and Sponsor will not be in any way responsible or liable for User Content. Sponsor may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in Sponsor’s sole judgment violates this Terms of Use or is otherwise objectionable. You understand that when using the Service you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent or objectionable. You agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Sponsor with respect to User Content. Sponsor expressly disclaims any and all liability in connection with User Content. If notified by a user or content owner that User Content allegedly does not conform to this Terms of Use, Sponsor may investigate the allegation and determine in its sole discretion whether to remove the User Content, which Sponsor reserves the right to do at any time and without notice.</p>

      <h2>2. Third Party Services and Linked Websites.</h2>
      <h3>2.1 Sponsor may provide tools through the Service that enable you to export information, including User Content, to third party services, including through features that allow you to link your account on Sponsor with an account on the third party service, such as Twitter or Facebook, or through our implementation of third party buttons (such as “like” or “share” buttons). By using these tools, you agree that Sponsor may transfer such information to the applicable third party service. Such third party services are not under Sponsor’s control, and Sponsor is not responsible for their use of your exported information. The Service may also contain links to third party websites. Such linked websites are not under Sponsor’s control, and Sponsor is not responsible for their content.</h3>
      <h2>3. Termination of Use; Discontinuation and Modification of the Service.</h2>
      <p>If you violate any provision of this Terms of Use, your permission to use the Service will terminate automatically. Additionally, Sponsor, in its sole discretion, may terminate your user account on the Service or suspend or terminate your access to the Service at any time, with or without notice. Sponsor also reserves the right to modify or discontinue the Service at any time (including, without limitation, by limiting or discontinuing certain features of the Service) without notice to you. Sponsor will have no liability whatsoever on account of any change to the Service or any suspension or termination of your access to or use of the Service.</p>

      <h2>4. Feedback.</h2>
      <p>If you provide feedback to Sponsor regarding the Service (“Feedback”), you acknowledge that the Feedback is not confidential and you authorize Sponsor to use that Feedback without restriction and without payment to you. Accordingly, you hereby grant to Sponsor a nonexclusive, royalty-free, fully-paid, perpetual, irrevocable, transferable, and fully sub-licensable right to use the Feedback in any manner and for any purpose. Sponsor provides no assurances that any reported problems will be resolved by Sponsor even if Sponsor elects to provide a response or information with the goal of addressing a problem.</p>

      <h2>5. Privacy Policy; Additional Terms.</h2>
      <h3>5.1 Privacy Policy.</h3>
      <p>Please read the Blue Spruce Concepts, Inc. Privacy Policy (follow the link at the bottom of <a href="https://www.bluesprucecopymachines.com">www.bluesprucecopymachines.com</a>) carefully for information relating to Sponsor’s collection, use, storage and disclosure of your personal information. The Blue Spruce Concepts, Inc. Privacy Policy is hereby incorporated by reference into, and made a part of, this Terms of Use.</p>

      <h3>5.2 Additional Terms.</h3>
      <p>Your use of the Service is subject to any and all additional terms, policies, rules, or guidelines applicable to the Service or certain features of the Service that Sponsor may post on or link to on the Service (the “Additional Terms”), such as end user license agreements for any downloadable applications that Sponsor may offer, or rules applicable to particular features or content on the Service, subject to Section 6 below. All such Additional Terms are hereby incorporated by reference into, and made a part of, this Terms of Use.</p>

      <h2>6. Modification of these Terms of Use.</h2>
      <p>Sponsor reserves the right, at its discretion, to change this Terms of Use on a going-forward basis at any time. Please check this Terms of Use periodically for changes. If a change to this Terms of Use materially modifies your rights or obligations, you will be required to accept such modified terms in order to continue to use the Service. Material modifications are effective upon your acceptance of such modified Terms of Use. Immaterial modifications are effective upon publication. For the avoidance of doubt, disputes arising under this Terms of Use will be resolved in accordance with this Terms of Use in effect that the time the dispute arose.</p>

      <h2>7. Ownership; Proprietary Rights.</h2>
      <p>The Service is owned and operated by Sponsor. The visual interfaces, graphics, design, compilation, information, data, computer code (including source code or object code), products, Software, services, and all other elements of the Service (the “Materials”) provided by Sponsor are protected by all relevant intellectual property and proprietary rights and applicable laws. All Materials contained in the Service are the property of Sponsor or our third party licensors. Except as expressly authorized by Sponsor, you may not make use of the Materials. Sponsor reserves all rights to the Materials not granted expressly in this Terms of Use.</p>

      <h2>8. Indemnity.</h2>
      <p>You agree that you will be responsible for your use of the Service, and you agree to defend, indemnify, and hold harmless Sponsor and each of their officers, directors, employees, consultants, affiliates, subsidiaries, agents, and distributors (collectively, the “Sponsor Entities”) from and against any and all claims, liabilities, damages, losses, and expenses, including reasonable attorneys’ fees and costs, arising out of or in any way connected with (i) your access to, use of, or alleged use of the Service; (ii) your violation of this Terms of Use or any representation, warranty, or agreements referenced in this Terms of Use, or any applicable law or regulation; (iii) your violation of any third party right, including without limitation any intellectual property right, publicity, confidentiality, property or privacy right; or (iv) any disputes or issues between you and any third party. Sponsor reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (and without limiting your indemnification obligations with respect to such matter), and in such case, you agree to cooperate with our defense of such claim.</p>

      <h2>9. Disclaimers; No Warranties.</h2>
      <p>THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS, WITHOUT WARRANTY OR CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE SPONSOR ENTITIES SPECIFICALLY (BUT WITHOUT LIMITATION) DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING BUT NOT LIMITED TO (i) ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (ii) ANY WARRANTIES ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE. SPONSOR ENTITIES DO NOT WARRANT THAT THE SERVICE OR ANY PART OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED.</p>
      <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE SERVICE OR ANY MATERIALS OR CONTENT AVAILABLE ON OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY REGARDING THE SPONSOR ENTITIES OR THE SERVICE THAT IS NOT EXPRESSLY STATED IN THIS TERMS OF USE. YOU ASSUME ALL RISK FOR ALL DAMAGES THAT MAY RESULT FROM YOUR USE OF OR ACCESS TO THE SERVICE, YOUR DEALINGS WITH OTHER SERVICE USERS, AND ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE. YOU UNDERSTAND AND AGREE THAT YOU USE THE SERVICE AND USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN MATERIALS OR CONTENT THROUGH THE SERVICE AND ANY ASSOCIATED SITES OR SERVICES AT YOUR OWN DISCRETION AND RISK, AND AS BETWEEN YOU AND THE SPONSOR ENTITIES, YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PERSON OR PROPERTY (INCLUDING YOUR PERSONAL PROPERTY USED IN CONNECTION WITH THE SERVICE) OR LOSS OF DATA OR ANY OTHER LOSS THAT RESULTS FROM THE USE OF THE SERVICE OR THE DOWNLOAD OR USE OF SUCH MATERIALS OR CONTENT.</p>
      <p>SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OF WARRANTIES AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>
      <h2>10. Limitation of Liability.</h2>
      <p>IN NO EVENT WILL THE SPONSOR ENTITIES BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE OR ANY OTHER LEGAL THEORY, WHETHER OR NOT THE SPONSOR ENTITIES HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
      <p>YOU AGREE THAT THE AGGREGATE LIABILITY OF THE SPONSOR ENTITIES TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR ANY INABILITY TO USE THE SERVICE (INCLUDING ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE) OR OTHERWISE UNDER THIS TERMS OF USE, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO THE GREATER OF (i)THE AMOUNTS YOU HAVE PAID TO SPONSOR FOR ACCESS TO AND USE OF THE SERVICE IN THE TWELVE MONTHS PRIOR TO THE CLAIM OR (ii)$100.</p>
      <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES. ACCORDINGLY, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
      <p>EACH PROVISION OF THESE TERMS OF USE THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS TO ALLOCATE THE RISKS UNDER THIS TERMS OF USE BETWEEN THE PARTIES. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS OF USE. THE LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>

      <h2>11. Governing Law.</h2>
      <p>This Terms of Use is governed by the laws of the State of CO without regard to conflict of law principles. To the extent that any lawsuit or court proceeding is permitted hereunder, you and Sponsor agree to submit to the personal and exclusive jurisdiction of the state courts and federal courts located within the state of CO for the purpose of litigating all such disputes. Sponsor operates the Service from its offices in CO and it makes no representation that Materials included in the Service are appropriate or available for use in other locations.</p>

      <h2>12. General.</h2>
      <p>This Terms of Use, together with the Privacy Policy and any other agreements expressly incorporated by reference, constitute the entire and exclusive understanding and agreement between you and Sponsor regarding your use of and access to the Service, and except as expressly permitted above may be amended only by a written agreement signed by authorized representatives of all parties to this Terms of Use. You may not assign or transfer this Terms of Use or your rights hereunder, in whole or in part, by operation of law or otherwise, without our prior written consent. Sponsor may assign this Terms of Use at any time without notice. The failure to require performance of any provision will not affect Sponsor’s right to require performance at any time thereafter, nor will a waiver of any breach or default of this Terms of Use or any provision of this Terms of Use constitute a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in this Terms of Use is for convenience only and will not have any impact on the interpretation of particular provisions. If any part of this Terms of Use is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible and the remaining parts will remain in full force and effect. Upon termination of this Terms of Use, any provision that by its nature or express terms should survive will survive such termination or expiration.</p>

      <h2>13. Dispute Resolution and Arbitration.</h2>
      <h3>13.1 Generally.</h3>
      <p>In the interest of resolving disputes between you and Sponsor in the most expedient and cost effective manner, you and Sponsor agree that any and all disputes arising in connection with this Terms of Use and your use of, and access to, the Service will be resolved by binding arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes, but is not limited to all claims arising out of or relating to any aspect of this Terms of Use, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory, and regardless of whether the claims arise during or after the termination of this Terms of Use. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THIS TERMS OF USE, YOU AND SPONSOR ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</p>

      <h3>13.2 Exceptions.</h3>
      <p>Notwithstanding Section 13.1, we both agree that nothing in this Terms of Use will be deemed to waive, preclude, or otherwise limit either of our right to: (i) bring an individual action in small claims court; (ii) pursue enforcement actions through applicable federal, state, or local agencies where such actions are available; (iii) seek injunctive relief in a court of law; or (iv) to file suit in a court of law to address intellectual property infringement claims.</p>

      <h3>13.3 Arbitrator.</h3>
      <p>Any arbitration between you and Sponsor will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by this Terms of Use, and will be administered by the AAA. The AAA Rules and filing forms are available online at <a href="https://www.adr.org">www.adr.org</a>, by calling the AAA at 1-800-778-7879, or by contacting Sponsor.</p>
      <h3>13.4 Notice; Process.</h3>
      <p>A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or if we do not have a physical address on file for you, by submitting a form <a href="/tos-contact">here</a>: TOS Contact. The Notice must: (i) describe the nature and basis of the claim or dispute; and (ii) set forth the specific relief sought (“Demand”). We agree to use good faith efforts to resolve the claim directly, but if we do not reach an agreement to do so within thirty (30) days after the Notice is received, you or Sponsor may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or Sponsor must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. If our dispute is finally resolved through arbitration in your favor, Sponsor will pay you: (a) the amount awarded by the arbitrator, if any; (b) the last written settlement amount offered by Sponsor in settlement of the dispute prior to the arbitrator’s award; or (c) $1,000, whichever is greater.</p>

      <h3>13.5 Fees.</h3>
      <p>If you commence arbitration in accordance with this Terms of Use, Sponsor will reimburse you for your payment of the filing fee, unless your claim is for greater than $10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearings will take place at a location to be agreed upon in CO, provided that if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted: (i) solely on the basis of documents submitted to the arbitrator; (ii) through a non-appearance based telephonic hearing; or (iii) by an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In such case, you agree to reimburse Sponsor for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator will issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within fourteen (14) days of the arbitrator’s ruling on the merits. In the event of a dispute, and unless otherwise prohibited by law or expressly noted herein, each party will bear their own attorney’s fees and other costs.</p>

      <h3>13.6 No Class Actions.</h3>
      <p>YOU AND SPONSOR AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Sponsor agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.</p>

      <h3>13.7 Modifications.</h3>
      <p>If Sponsor makes any future change to this arbitration provision (other than a change to Sponsor’s address for Notice), you may reject any such change by sending us written notice within thirty (30) days of the change to Sponsor’s address for Notice, in which case your account with Sponsor will immediately be terminated and this arbitration provision, as in effect immediately prior to the amendments you reject will survive.</p>

      <h3>13.8 Enforceability.</h3>
      <p>If Section 13.6 is found to be unenforceable or if the entirety of this Section 13 is found to be unenforceable, then the entirety of this Section 13 will be null and void and, in that case, the parties agree that the exclusive jurisdiction and venue described in Section 11 will govern any action arising out of or related to this Terms of Use.</p>

      <h2>14. Consent to Electronic Communications.</h2>
      <p>By using the Service, you consent to receiving certain electronic communications from us as further described in our Privacy Policy. Please read our Privacy Policy to learn more about your choices regarding our electronic communications practices. You agree that any notices, agreements, disclosures, or other communications that Sponsor sends to you electronically will satisfy any legal communication requirements, including that such communications be in writing.</p>
    </div>
    )
}
const styles = {
 container: {
    padding: 20,
    maxWidth: 800,
    margin: "0 auto",
    fontFamily: "Arial, sans-serif",
  },
}